package org.radarbase.oura.converter

import com.fasterxml.jackson.databind.JsonNode
import okhttp3.Headers
import java.time.Instant
import org.radarbase.oura.request.OuraRequestGenerator.Companion.JSON_READER

/**
 * Abstract class to help convert Fitbit data to Avro Data.
 */
interface OuraDataConverter: PayloadToSourceRecordConverter {
    /** Process the JSON records generated by given request.  */
    fun processRecords(
            dateRange: DateRange,
            root: JsonNode,
            timeReceived: Double
    ): Sequence<Result<TopicData>>

    override fun convert(request: OuraRequest, headers: Headers, data: ByteArray): Sequence<Result<TopicData>> {
        val node = JSON_READER.readTree(data)

        return this.processRecords(request.getDateRange(), node, Instant.now().epochSecond.toDouble())
    }
}