package org.radarbase.oura.converter

import com.fasterxml.jackson.databind.JsonNode
import okhttp3.Headers
import java.time.Instant
import org.radarbase.oura.request.OuraRequestGenerator.Companion.JSON_READER
import org.radarbase.oura.request.RestRequest

/**
 * Abstract class to help convert Fitbit data to Avro Data.
 */
interface OuraDataConverter: RecordConverter {
    /** Process the JSON records generated by given request.  */
    fun processRecords(
            root: JsonNode
    ): Sequence<Result<TopicData>>

    override fun convert(request: RestRequest, headers: Headers, data: ByteArray): Sequence<Result<TopicData>> {
        val node = JSON_READER.readTree(data)

        return this.processRecords(node)
    }
}