package org.radarbase.oura.converter

import com.fasterxml.jackson.databind.JsonNode
import okhttp3.Headers
import java.time.Instant

/**
 * Abstract class to help convert Fitbit data to Avro Data.
 */
open class OuraDailySleepConverter: PayloadToSourceRecordConverter {
    /** Process the JSON records generated by given request.  */
    override fun processRecords(
            dateRange: DateRange,
            root: JsonNode,
            timeReceived: Double
    ): Sequence<Result<TopicData>>

}