/*
 * Copyright 2026 Onsentia
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

package org.radarbase.huawei.converter

import com.fasterxml.jackson.databind.JsonNode
import okhttp3.Headers
import org.radarbase.huawei.request.HuaweiRequestGenerator.Companion.JSON_READER
import org.radarbase.huawei.request.RestRequest
import org.radarbase.huawei.user.User
import java.time.Instant

/**
 * Converts a Huawei Health Kit HTTP JSON response body to zero or more [TopicData] records.
 */
interface HuaweiDataConverter : RecordConverter {
    /** Process the JSON records generated by given request. */
    fun processRecords(
        root: JsonNode,
        user: User,
    ): Sequence<Result<TopicData>>

    override fun convert(
        request: RestRequest,
        headers: Headers,
        data: ByteArray,
    ): List<TopicData> {
        val node = JSON_READER.readTree(data)

        return this.processRecords(node, request.user)
            .mapNotNull { r ->
                r.fold(
                    { it },
                    {
                        logger.error("Data conversion failed.. " + it.message)
                        null
                    },
                )
            }
            .toList()
    }

    fun Instant.toEpoch(): Double = this.toEpochMilli() / 1000.0
}
