
group = 'org.radarbase'
version = '0.0.1'

apply plugin: 'maven-publish'

repositories {
    mavenCentral()
}

dependencies {
    implementation libs.kotlin.stdlib

    implementation libs.okhttp

    implementation libs.radar.schemas.commons

    implementation libs.jackson.annotations

    implementation libs.jackson.databind

    implementation libs.avro

    implementation libs.jackson.datatype.jsr310

    testImplementation libs.kotlin.test

    testImplementation libs.kotlin.test.junit
}

project.afterEvaluate {
    publishing {
        publications {
            library(MavenPublication) {
                setGroupId "$group"
                setArtifactId "google-health-library"
                version "$version"
                from components.java
            }
        }
    }
}
